### ISSUE TITLE
Intellij imports do not get the @ prefix

### ISSUE THREAD

**Issue by rferreira** [casid/jte-intellij#10]
start with a template like this: 
```
@param Map<String, Object> context

```
IntelliJ will ask you to import map, and you will end up with "import java.util.Map" not "@import java.util.Map"

**Comment by casid** [comment]
@rferreira when I start with this:

```
@param Map<String, Object> context
```


And press alt+enter on `Map`, I end up with this:

```
@param java.util.Map<String, Object> context
```

Currently the first import needs to be done by hand.
After that IntelliJ can access the imports of the injected class and new classes are properly imported.

So far I haven't found a way around this.

**Comment by rferreira** [comment]
Thanks @casid !
