### ISSUE TITLE
Multi-module maven project and JSP to JTE conversion using IDEA plugin

### ISSUE THREAD

**Issue by izogfif** [casid/jte-intellij#12]
I have a multi-module Maven project. I created `Module1JspToJteConverter` that extends `JspToJteConverter` in `module1`. Converted `.tag` file inside `module1` using Intellij IDEA plugin. Everything was fine.
Then I created `Module2JspToJteConverter` in `module2`. It has different settings (e.g. `converter.setPrefix` contains different list of `@import` directives). When I open in Intellij IDEA `.tag` file that resides inside `module2` and go to menu `Code->Convert JSP file to jte file`, `Module1JspToJteConverter` starts instead of `Module2JspToJteConverter`.

**Comment by casid** [comment]
I transferred this issue over to the jte-intellij plugin.

And I think I have a fix for it. It now works with multiple modules in my dummy project.

I'll try to release a new version of the plugin this weekend.

**Comment by casid** [comment]
I've uploaded a new version of the plugin!

```
Thank you for submitting a 1.4.1 version of jte plugin, it has been successfully uploaded to the plugins repository and now pending JetBrains' review and approval in order to be publicly available.

All new updates are normally reviewed within two business days. You will receive a notification as soon as status of this review changes.
```

**Comment by izogfif** [comment]
@casid can you add a tag and release for 1.4.1 version of this plugin? So that it can be downloaded from https://github.com/casid/jte-intellij/releases page. "Two business days" means that it won't be available from Intellij IDEA plugin marketplace until at least Tuesday.

**Comment by izogfif** [comment]
@casid 
I've installed the plugin and I'm getting this error message now:
```
Could not locate class 'gg.jte.convert.jsp.JspToJteConverter' on the classpath. You're probably missing the jte-jsp-converter dependency.
```
I've even changed scope from `test` to `compile` and added code
```
JspToJteConverter g = new JspToJteConverter(Path.of("/"), Path.of("/"), "");
```
in one of .java files inside `src/main/java` of the module. The project compiled successfully, i.e. the issue is not that I forgot to add a dependency.

After studying your commit, I think I found the issue. Method `com.intellij.psi.search.GlobalSearchScope.moduleScope` has this JavaDoc:
> Returns module scope including sources and tests, **excluding libraries and dependencies**.

Maybe you should use `GlobalSearchScope.moduleWithDependenciesAndLibrariesScope` instead?

**Comment by casid** [comment]
Thanks for the investigation. I released a hotfix version of the plugin.
