### ISSUE TITLE
Gradle 7 build fix

### ISSUE THREAD

**Issue by izogfif** [casid/jte-intellij#13]
`testCompile` dependency of `Java` plugin was deprecated back in Gradle 4.8 (if I'm not mistaken) and `testImplementation` which was introduced in Gradle 3.4 should be used instead.
Build fails on Gradle 7.1.1 (Java 16 is supported in Gradle 7 and newer only).
Please edit `build.gradle`: replace
```
dependencies {
    testCompile group: 'junit', name: 'junit', version: '4.13.1'
}
```
with
```
dependencies {
    testImplementation group: 'junit', name: 'junit', version: '4.13.1'
}
```

**Comment by casid** [comment]
Thanks for reporting. I changed to `testImplementation`
