### ISSUE TITLE
Tagged templates are not supported by IntelliJ plugin

### ISSUE THREAD

**Issue by dzikoysk** [casid/jte-intellij#39]
[Tagged templates](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#tagged_templates) seems to be unrecognized by the IntelliJ plugin:

![obraz](https://github.com/casid/jte/assets/4235722/03588a83-dfb3-4457-86c6-f281acb7c0ba)

The code compiles properly tho. To be fair, I'm not sure if it interferes with one of the jte features, but I couldn't find anything related in docs.

**Comment by casid** [comment]
I moved this to the IntelliJ project. Support for this should be covered by the regular JS abilities of IntelliJ. What error message do you get when hovering over the red markers?

**Comment by dzikoysk** [comment]
Yeah, sorry, I forgot to attach this:

![obraz](https://github.com/casid/jte-intellij/assets/4235722/789378f4-b953-4cce-a315-f77600e1236a)

**Comment by casid** [comment]
Thanks, yes, that message is coming from the jte plugin and is just wrong.
