### ISSUE TITLE
JSP-to-Jte Converter fails when classes using JspToJteConverter are used in multiple modules

### ISSUE THREAD

**Issue by Huppys** [casid/jte-intellij#40]
I am attempting to migrate a JSP template to JTE. Within my IntelliJ project, there are two modules, each containing a class that extends the JspToJteConverter.

During the execution of the conversion process, the converter class within the first project is located; however, the template is located in the second module.

Connected to #12.

**Comment by Huppys** [comment]
As a workaround, I temporarily deactivate the module whose converter I don't want to be used by the IntelliJ plugin. That way I can convert the desired template.

**Comment by casid** [comment]
Thank you for reporting and helping with the fix. I'm going to release a new plugin version soon.
