### ISSUE TITLE
FR/Question: make Kotlin plugin dependency optional

### ISSUE THREAD

**Issue by woj-tek** [casid/jte-intellij#47]
Hi,
(there is no "discussion" section hence creating an issue)

Would it be possible to make Kotlin dependency optional? I'm not really using it and while trying to make IDEA go a bit easier on resources I notice that `jte` plugin (200K) required Kotlin plugin (150M).

**Comment by casid** [comment]
Thanks for the suggestion.
I believe this would require two different plugins, I guess?
Unfortunately, I don't have much time maintaining the plugin and maintaining two would be too much for me I fear.

Currently upgrading to the 2.0 version of the intellij gradle plugin and it is quite a pain ^^
