### ISSUE TITLE
intellij "Cannot resolve MVC view"

### ISSUE THREAD

**Issue by don41382** [casid/jte-intellij#52]
My Intellij can't resolve the view path. 

Any idea how to fix this?

**Comment by casid** [comment]
Closing this, as there is a solution by @qual-it-solutions. Thanks!

**Comment by official-wizard** [comment]
I get this issue unless the extension is explicitly included. e.g. `path/index.jte` resolves fine but `path/index` does not.

**Comment by pyiso80** [comment]
> Closing this, as there is a solution by [@qual-it-solutions](https://github.com/qual-it-solutions). Thanks!

I believe the workaround by @ qual-it-solutions doesn't work perfect. It works only when we have the file extension (as mentioned in the comment @ official-wizard)

Although I wouldn't say this issue as critical, i wish IntelliJ behave correctly. The inspection is already there and just have to make it work correctly.
